spring:
  datasource:
    url: jdbc:postgresql://localhost/jpashop
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
#        show_sql: true
        format_sql: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

spring.h2.console.enable: true